apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qubiva.fullname" . }}-artifacts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qubiva.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.artifacts.accessMode }}
  {{- with .Values.artifacts.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.artifacts.storageSize }}
