apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "qubiva.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qubiva.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status", "pods/exec"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "qubiva.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qubiva.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "qubiva.fullname" . }}-app
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "qubiva.fullname" . }}-runner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qubiva.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "qubiva.fullname" . }}-runner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qubiva.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.runnerServiceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "qubiva.fullname" . }}-runner
  apiGroup: rbac.authorization.k8s.io
