apiVersion: v1
kind: Service
metadata:
  name: {{ include "qubiva.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qubiva.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "qubiva.selectorLabels" . | nindent 4 }}
    component: app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
